.\" Manpage for demo.
.TH man 1 "28 Nov 2017" "0.1" "demo man page"
.SH NAME
demo \- Just say Hi!
.SH SYNOPSIS
demo [options]
.SH DESCRIPTION
demo is simple command.
.SH OPTIONS
The demo does not take any options.
.SH SEE ALSO
demo-again(1), hello(1), hi(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Demo (demo@develop)
