
default: help
.PHONY: default


help:
	@./help.sh
.PHONY: help


create:
	@./create.sh
.PHONY: create


build:
	@./build.sh
.PHONY: build


install:
	@./install.sh
.PHONY: install


remove:
	@./remove.sh
.PHONY: remove


clean:
	rm -f demo.deb
.PHONY: clean
