
default: help
.PHONY: default


help:
	@echo 'Usage:'
	@echo '	make'
	@echo '	make help'
	@echo '	make create'
	@echo '	make build'
	@echo '	make install'
	@echo '	make remove'
.PHONY: help


create:
	@./create.sh
.PHONY: create


build:
	@./build.sh
.PHONY: build


install:
	@./install.sh
.PHONY: install


remove:
	@./remove.sh
.PHONY: remove


clean:
	rm -f demo.deb
.PHONY: clean
